### PR TITLE
Added heal count split-brain metric to gluster dashboard

### PR DESCRIPTION
**Pull request by anmolsachan**
Issue: https://github.com/gluster/gluster-mixins/issues/50

Signed-off-by: Anmol Sachan <anmol13694@gmail.com>

### CODE REVIEW

**Comment by anmolsachan** [comment]
@cloudbehl Please review and tag for GCS 0.5

**Comment by shtripat** [comment]
The gluster-prometheus PR https://github.com/gluster/gluster-prometheus/pull/120 is still under review.

**Review by shtripat — COMMENTED** [review]
The changes look fine

**Comment by cloudbehl** [comment]
@anmolsachan please create an issue for this.

**Pull request merged**
