### PR TITLE
Added job label to rules

### PR DESCRIPTION
**Pull request by anmolsachan**
fixes : #23 
Signed-off-by: Anmol Sachan <anmol13694@gmail.com>

### CODE REVIEW

**Comment by umangachapagain** [comment]
Have you tested this?
How is the result different?

**Comment by umangachapagain** [comment]
my only concern here is about using a generic `job` label for grouping in query that is meant specifically for the metrics that is exposed by `job='gluster-exporter'`.

In the current single cluster, single job setup this works as expected but can we be sure that it will be the same in a multi cluster, multi job setup or some other complex use case?

I don't have much knowledge in this area, but I have a feeling that we might run into some issue later such as duplicate alerting based on similar metrics coming in from different job? alerting on metrics from job that we do not care about?

**Comment by anmolsachan** [comment]
@umangachapagain I understand the concern here regarding alerts. Multi-cluster is the use case that has to be supported. I would say lets test that scenario in the dev setups and see what obstacles we face.

**Comment by cloudbehl** [comment]
No more required!

**Pull request closed without merging**
