### PR TITLE
Brick and Volume Status

### PR DESCRIPTION
**Pull request by umangachapagain**
Issue: gluster/gluster-mixins/issues/5
Signed-off-by: Umanga Chapagain <chapagainumanga@gmail.com>

### CODE REVIEW

**Comment by umangachapagain** [comment]
It is fixed but can be made configurable.
Should we make it configurable or should we have a fixed decided value? 

This should be configurable only if there are dependent factors like infrastructure, or self-heal for the bricks.

@cloudbehl @anmolsachan Thoughts?

**Comment by umangachapagain** [comment]
Tested. Works fine.

**Comment by cloudbehl** [comment]
> It is fixed but can be made configurable.
> Should we make it configurable or should we have a fixed decided value?

I agree this should be configurable for each entity and we don't need to go inside the code to change these kind of configrations.

**Comment by umangachapagain** [comment]
> > It is fixed but can be made configurable.
> > Should we make it configurable or should we have a fixed decided value?
> 
> I agree this should be configurable for each entity and we don't need to go inside the code to change these kind of configrations.

This is not something anyone should be changing. If the status becomes `down` we need to immediately alert it and `1m` is the standard followed for alerts like these.

**Comment by shtripat** [comment]
> > > It is fixed but can be made configurable.
> > > Should we make it configurable or should we have a fixed decided value?
> > 
> > 
> > I agree this should be configurable for each entity and we don't need to go inside the code to change these kind of configrations.
> 
> This is not something anyone should be changing. If the status becomes `down` we need to immediately alert it and `1m` is the standard followed for alerts like these.

Ack. Thats fine and the PR looks fine otherwise.

**Comment by cloudbehl** [comment]
@shtripat Had chat with umaga related to the configuration changes to pass the time value. He has made the required change. please review @shtripat @anmolsachan

**Pull request merged**
